### ISSUE TITLE
P136 code errata

### ISSUE THREAD

**Issue by pls-kick-me** [PacktPublishing/Learning-GDScript-by-Developing-a-Game-with-Godot-4#16]
Instead of
```
@export_range(0, 10) health: int = 10
```
should be 
```
@export_range(0, 10) var health: int = 10
```

**Comment by bsingha27** [comment]
Hi @pls-kick-me, The README has been updated to reflect the erratum. We are closing this issue for now. If you encounter any further issues with the code, please feel free to open a new one.
Thanks.
