### ISSUE TITLE
2nd code line syntax errors - Book Errata

### ISSUE THREAD

**Issue by Slothy2406** [PacktPublishing/Learning-GDScript-by-Developing-a-Game-with-Godot-4#2]
Page 52

not too sure if this is a suppose to have this many mistakes in it?

What does the following code snippet print out?

var number_of_lives = 0
Print("You live" if number_of_lives > 0

Captial P for print
no end ) 
and I believe it needs a else statement as well

**Comment by bsingha27** [comment]
Hi, 
Thank you for bringing this to our attention. We've updated the README with both the book errata you've raised, which includes corrections for the mistakes you've pointed out.
