### ISSUE TITLE
P136 error in text

### ISSUE THREAD

**Issue by octopuddle** [PacktPublishing/Learning-GDScript-by-Developing-a-Game-with-Godot-4#4]
At the bottom of the page, it says

In the preceding code excerpt, we export the health variable and specify that it should be a number between 0 and 10, including the outer values of 0 and 20.

Should that be

including the outer values of 0 and 10.

**Comment by bsingha27** [comment]
Hi @octopuddle, The README has been updated to reflect the erratum. We're closing this issue now.
