### ISSUE TITLE
Figure 8.10 text mismatch

### ISSUE THREAD

**Issue by octopuddle** [PacktPublishing/Learning-GDScript-by-Developing-a-Game-with-Godot-4#5]
P177 - Organizing scene files

The instructions are:

Add the following folders in the root folder of our project:
• parts:
� environment
� player
• screens:
� game

In figure 8.10 the folder is called arena, instead of environment.

**Comment by SanderVanhove** [comment]
The name `Arena` in general is misused within that chapter. Thanks for letting us know!
